<a href="https://colab.research.google.com/github/shravs45/Machine-Learning/blob/Linear-Regression/Linear_Regression_Cars_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A German Automobile company Caltech Auto is planning to set up their manufacturing unit in India. Caltech is interested in understanding the factors that affect the price of cars, also wants to know which features contribute the most to car price.



Accordingly, Caltech has collected a large dataset of different types of cars across German market.



**Caltech wants to predict the price of the car and how does other features affect it.**

You being a Data-scientist are expected to build a Linear Regression model and Regularize it. Before, building a model cleaning the data is an important aspect to be noted.

In [135]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [3]:
cars_df=pd.read_csv('/content/sample_data/Cars.csv')
cars_df.head()

                    carname fueltype aspiration  ... citympg highwaympg    price
0        alfa-romero giulia      gas        std  ...      21         27  13495.0
1       alfa-romero stelvio      gas        std  ...      21         27  16500.0
2  alfa-romero Quadrifoglio      gas        std  ...      19         26  16500.0
3               audi 100 ls      gas        std  ...      24         30  13950.0
4                audi 100ls      gas        std  ...      18         22  17450.0

[5 rows x 24 columns]

In [56]:
columns = cars_df.isnull().sum()
null_column_names=[]
for index,value in columns.items():
  if value>0:
    null_column_names.append(index)

#print(null_column_names)
#cars_df[cars_df.isna().any(axis=1)]

In [64]:
"""Filling Missing Values by imputing those numeric columns using Median strategy"""
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
imputed_data = imputer.fit_transform(cars_df[null_column_names])

for i in range(len(null_column_names)):
  cars_df[null_column_names[i]]=imputed_data[:,i]

In [132]:
"""Finding mean of enginesize"""
print("EngineSize Mean: {}".format(cars_df['enginesize'].mean()))

"""Find correlation of 'enginesize' with 'price' after imputing"""
cars_df[['enginesize','price']].corr()

categorical_columns=[]
continuousVar_columns=[]
"""Create another data frame to store all the categorical data
 and perform the below operations on this dataframe"""
for index,value in cars_df.dtypes.items():
  if value==object:
    categorical_columns.append(index)
  else:
    continuousVar_columns.append(index)

cat_columns=pd.DataFrame(cars_df,columns=categorical_columns)

"""Split the names of the cars (by spaces) keeping only its first name"""
cat_columns['carname']=cat_columns['carname'].str.split(' ').str[0]

"""Some car names are misspelled so replace the misspelled names with correct spelling"""
#Try using .loc[row_indexer,col_indexer] = value instead
cat_columns.loc[cat_columns['carname']=='toyouta','carname']='toyota'

"""Print the count of ‘toyota’ cars in carname column"""
cat_columns[cat_columns['carname']=='toyouta']['carname'].count()

"""Create another dataframe consisting of all the continuous variables 
(wheelbase, carlength, carwidth, carheight, curbweight, enginesize, 
borratio, compressionratio, horsepower, peakrpm, citympg, highwaympg, price)
 and include only 'carname' as categorical variable 
 [Hint: The "carname" column should only take the 'first_name' of the car as done in Step no.6]"""
cont_columns=pd.DataFrame(cars_df,columns=continuousVar_columns)
cont_columns['carname']=cat_columns['carname']

""" Apply an encoding technique to convert categorical values to numerical values 
and print last 2 rows of data(Hint: Use get_dummies)"""
car_info=pd.get_dummies(cont_columns,prefix="_",drop_first=True)
print(car_info.tail(2))

EngineSize Mean: 122.70731707317073
     wheelbase  carlength  carwidth  ...  __volkswagen  __volvo  __vw
203      109.1      188.8      68.9  ...             0        1     0
204      109.1      188.8      68.9  ...             0        1     0

[2 rows x 40 columns]

     wheelbase  carlength  carwidth  ...  __volkswagen  __volvo  __vw
0         88.6      168.8      64.1  ...             0        0     0
1         88.6      168.8      64.1  ...             0        0     0
2         94.5      171.2      65.5  ...             0        0     0
3         99.8      176.6      66.2  ...             0        0     0
4         99.4      176.6      66.4  ...             0        0     0
..         ...        ...       ...  ...           ...      ...   ...
200      109.1      188.8      68.9  ...             0        1     0
201      109.1      188.8      68.8  ...             0        1     0
202      109.1      188.8      68.9  ...             0        1     0
203      109.1      188.8      68.9  ...             0        1     0
204      109.1      188.8      68.9  ...             0        1     0

[205 rows x 40 columns]

In [133]:
"""Based on the data generated in the above step, build a linear regression model 
and find its accuracy and y-intercept rounded to 3 decimal places. 
Use 'price' as response variable and all other variables as predictors 
(Hint: Split the data into 80/20 train/test pattern by keeping random state=5)"""
regressor = LinearRegression()

y=car_info['price']
X=car_info
X.drop('price',axis=1,inplace=True)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state=5)
regressor.fit(X_train,y_train)
print(regressor.score(X_test,y_test))
print(regressor.intercept_)

0.8713428612535146
20736.98941545242

In [137]:
"""Regularize the model using Ridge and Lasso techniques
and find out the score of each respectively 
rounded to 3 decimal places(Hint: Set alpha=0.01)"""

ridge_reg = Ridge(alpha=0.01,normalize=True)
ridge_reg.fit(X_train,y_train)
print(ridge_reg.score(X_test,y_test))

Lasso_reg = Lasso(alpha=0.01,normalize=True)
Lasso_reg.fit(X_train,y_train)
print(Lasso_reg.score(X_test,y_test))

0.8899895139439498
0.8719442271759903

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples).
  FutureWarning,